module.exports.descriptors = [
    'Tranquil',
    'Sacred',
    'Misty',
    'Verdant',
    'Serene',
    'Whispering',
    'Echoing',
    'Rustling',
    'Golden',
    'Wild',
    'Hidden',
    'Shady',
    'Blooming',
    'Majestic',
    'Starlit',
    'Lotus',
    'Peepal',
    'Jasmine',
    'Monsoon',
    'Dusky'
];

module.exports.places = [
    'Ghats',
    'Meadows',
    'Valley',
    'Woods',
    'Hills',
    'Creek',
    'Grove',
    'Sanctuary',
    'Lakeview',
    'Ridge',
    'Riverbank',
    'Plateau',
    'Trail',
    'Spring',
    'Cliffs',
    'Glade',
    'Hollow',
    'Grasslands',
    'Pond',
    'Retreat',
    'Mangroves',
    'Tea Garden',
    'Banyan Camp'
];
